package curl

/*
#include <curl/curl.h>
*/
import "C"

// CURLcode
const (
	CURLINFO_TEXT         = C.CURLINFO_TEXT
	CURLINFO_HEADER_IN    = C.CURLINFO_HEADER_IN
	CURLINFO_HEADER_OUT   = C.CURLINFO_HEADER_OUT
	CURLINFO_DATA_IN      = C.CURLINFO_DATA_IN
	CURLINFO_DATA_OUT     = C.CURLINFO_DATA_OUT
	CURLINFO_SSL_DATA_IN  = C.CURLINFO_SSL_DATA_IN
	CURLINFO_SSL_DATA_OUT = C.CURLINFO_SSL_DATA_OUT
	CURLINFO_END          = C.CURLINFO_END
)

// generated ends
